/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        neo: {
          bg: '#FAF8F5',
          bgAlt: '#F4EFEA',
          bgHero: '#FBF8F2',
          bgAbout: '#FAF5ED',
          bgProjects: '#F4EFE6',
          bgExperience: '#121214',
          bgContact: '#FFFDF6',
          bgStatStrip: '#FFFFFF',
          card: '#FFFFFF',
          darkBg: '#121214',
          darkCard: '#1A1A1E',
          darkSurface: '#24242B',
          black: '#121212',
          yellow: '#FFE600',
          yellowHover: '#E6CF00',
          lime: '#A3E635',
          limeAlt: '#00F59B',
          pink: '#FF4365',
          pinkAlt: '#FF6B8B',
          blue: '#38BDF8',
          blueAlt: '#00D2FF',
          purple: '#A78BFA',
          orange: '#FB923C',
          muted: '#71717A',
          border: '#121212',
          darkBorder: '#F4F4F5',
        },
        dark: '#121214',
        darkSecondary: '#1A1A1E',
        primary: {
          DEFAULT: '#FFE600',
          50: '#FFFDE5',
          100: '#FFFACB',
          200: '#FFF697',
          300: '#FFF163',
          400: '#FFED3E',
          500: '#FFE600',
          600: '#CCA000',
          700: '#997800',
          800: '#665000',
          900: '#332800',
        },
        accent: {
          DEFAULT: '#A3E635',
          lime: '#A3E635',
          pink: '#FF4365',
          cyan: '#38BDF8',
          purple: '#A78BFA',
          orange: '#FB923C',
        },
      },
      fontFamily: {
        display: ['"Space Grotesk"', '"Plus Jakarta Sans"', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'neo-sm': '2px 2px 0px #121212',
        'neo': '4px 4px 0px #121212',
        'neo-md': '6px 6px 0px #121212',
        'neo-lg': '8px 8px 0px #121212',
        'neo-xl': '12px 12px 0px #121212',
        'neo-dark-sm': '2px 2px 0px #FFE600',
        'neo-dark': '4px 4px 0px #FFE600',
        'neo-dark-md': '6px 6px 0px #FFE600',
        'neo-dark-lg': '8px 8px 0px #FFE600',
        'neo-dark-white': '4px 4px 0px #FFFFFF',
        'neo-dark-white-lg': '8px 8px 0px #FFFFFF',
        'neo-dark-lime': '4px 4px 0px #A3E635',
        'neo-dark-pink': '4px 4px 0px #FF4365',
        'neo-dark-blue': '4px 4px 0px #38BDF8',
      },
      animation: {
        'marquee': 'marquee 25s linear infinite',
        'marquee-slow': 'marquee 40s linear infinite',
        'marquee-reverse': 'marquee-reverse 25s linear infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
      },
      screens: {
        '2xl': '1280px',
      },
    },
  },
  plugins: [],
}

